name: Owntone server
version: 0.1.0
slug: owntone-server
description: OwnTone is a DAAP (iTunes) media server with support for AirPlay, Chromecast, MPD, Spotify, web UI and internet radio.
arch:
  - armv7
  - aarch64
  - amd64

# Vi bruker host_network slik at mDNS/AirPlay annonsering funker ordentlig
host_network: true
host_dbus: false
host_ipc: false

# Port-mapping blir i praksis irrelevant med host_network=true,
# men brukes av HA til å lage riktig webui-lenke.
ports:
  3689/tcp: 3689

ports_description:
  3689/tcp: "Owntone web interface (DAAP/HTTP)"

map:
  - share:rw

# Ingress blir litt mer knotete å få til riktig via reverse proxy,
# så i første versjon bruker vi bare vanlig webui-lenk:
ingress: false
ingress_port: 0

webui: "http://[HOST]:3689/"

startup: services
boot: auto

# Vi lar Supervisor bygge Dockerfile lokalt (ingen ekstern image:)
# image: linuxserver/daapd

# Ingen HA-eksponert options i første versjon.
options: {}
schema: {}
