name: Owntone server
version: "29.0"
slug: owntone-server
description: OwnTone is a DAAP (iTunes) and MPD media server with support for AirPlay, Chromecast, MPD, Spotify and internet radio.
arch:
  - aarch64
  - amd64
  - armv7

# ❌ Fjern image:-linja helt – da bruker HA Dockerfile i stedet
# image: "owntone/owntone"

host_network: true

ports:
  3689/tcp: 3689

ports_description:
  3689/tcp: "Owntone web interface / DAAP"

# ✅ Viktig: mappe /share slik at vi har et sikkert skrivbart område på host
map:
  - share:rw

ingress: false
ingress_port: 0

webui: "http://[HOST]:[PORT:3689]"

startup: services
boot: auto
init: false

options: {}
schema: {}
